manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: Ocelot08
      url-base: https://github.com/Ocelot08
  projects:
    - name: zmk
      remote: Ocelot08
      revision: Ocelot08-test
      import: app/west.yml
  self:
    path: config
